[project]
name = "expense-splitter"

[tool.pyside6-project]
files = [
    "ExpenseSplitter.pyproject",
    "main.py",
    "qml/components/CurrencyComboBox.qml",
    "qml/components/ExpenseCard.qml",
    "qml/components/ParticipantCard.qml",
    "qml/components/SearchBar.qml",
    "qml/components/SettingsActionItem.qml",
    "qml/components/SettingsCard.qml",
    "qml/components/SettingsSection.qml",
    "qml/components/SettlementCard.qml",
    "qml/components/TripCard.qml",
    "qml/components/qmldir",
    "qml/dialogs/AddExpenseDialog.qml",
    "qml/dialogs/AddParticipantDialog.qml",
    "qml/dialogs/AddTripDialog.qml",
    "qml/dialogs/ConfirmationDialog.qml",
    "qml/dialogs/EditExpenseDialog.qml",
    "qml/dialogs/EditTripDialog.qml",
    "qml/dialogs/qmldir",
    "qml/main.qml",
    "qml/pages/HomePage.qml",
    "qml/pages/SettingsPage.qml",
    "qml/pages/TripPage.qml",
    "qml/pages/TripPage/ExpensesTab.qml",
    "qml/pages/TripPage/ParticipantsTab.qml",
    "qml/pages/TripPage/SettlementsTab.qml",
    "qml/popups/ParticipantListPopup.qml",
    "qml/popups/ParticipantMultiSelectPopup.qml",
    "qml/popups/ToastPopup.qml",
    "qml/popups/qmldir",
    "qml/theme/ThemeManager.qml",
    "qml/theme/qmldir",
    "resources.qrc",
    "src/data/trip_repository.py",
    "src/file_actions.py",
    "src/models.py",
    "src/services/settlement_service.py",
    "src/services/share_service.py",
    "src/settings_manager.py",
    "src/trip_manager.py",
]
